"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type Row = Record<string, string | number | boolean | null>;
type Data = {
  setupRequired?: boolean; canBootstrap?: boolean; email?: string; name?: string; error?: string;
  profile?: { email: string; name: string; role: string }; summary?: Row;
  students?: Row[]; clubs?: Row[]; rooms?: Row[]; events?: Row[]; levels?: Row[]; achievements?: Row[]; rewards?: Row[]; transactions?: Row[]; posts?: Row[];
};

const sections = ["Обзор","Студенты","Мероприятия","Клубы","Публикации","Помещения","DC Coins","Достижения","Магазин наград"];

async function callApi(method: "GET"|"POST", body?: Record<string, unknown>) {
  const response = await fetch("/api/manage", { method, headers: body ? { "content-type":"application/json" } : undefined, body: body ? JSON.stringify(body) : undefined });
  const data = await response.json() as Data & { ok?: boolean };
  if (!response.ok) throw new Error(data.error || "Ошибка сервера");
  return data;
}

export default function ManageClient({ signedInName, signedInEmail }: { signedInName: string; signedInEmail: string }) {
  const [data,setData]=useState<Data|null>(null); const [section,setSection]=useState("Обзор"); const [modal,setModal]=useState<string|null>(null); const [roleTarget,setRoleTarget]=useState<Row|null>(null); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState("");
  const load=useCallback(async()=>{try{setData(await callApi("GET"))}catch(e){setData({error:e instanceof Error?e.message:"Ошибка"})}},[]);
  useEffect(()=>{void load()},[load]);
  const act=async(payload:Record<string,unknown>,success:string)=>{setBusy(true);try{await callApi("POST",payload);setModal(null);setNotice(success);await load();window.setTimeout(()=>setNotice(""),2500)}catch(e){setNotice(e instanceof Error?e.message:"Ошибка")}finally{setBusy(false)}};
  if(!data) return <div className="manageLoading"><div className="brandMark"><span>D</span></div><p>Подключаем DOSTEAM HUB…</p></div>;
  if(data.error&&!data.setupRequired) return <div className="manageLoading error"><div className="brandMark"><span>!</span></div><h2>Доступ не открыт</h2><p>{data.error}</p><a href="/">Вернуться на сайт</a></div>;
  if(data.setupRequired) return <Setup data={data} busy={busy} onSetup={(form)=>act({action:"bootstrap",...form},"DOSTEAM HUB настроен")}/>;

  return <div className="manageShell">
    <aside className="manageSide"><a href="/" className="manageBrand"><div className="brandMark"><span>D</span></div><div><b>DOSTEAM</b><small>CONTROL CENTER</small></div></a><nav><p>УПРАВЛЕНИЕ</p>{sections.map(x=><button key={x} className={section===x?"active":""} onClick={()=>setSection(x)}><span>{icon(x)}</span>{x}</button>)}</nav><div className="manageUser"><span>BK</span><div><b>{signedInName}</b><small>{signedInEmail}</small></div></div><a className="manageSignout" href="/api/auth/logout">Выйти</a></aside>
    <main className="manageMain"><header><div><span>АДМИНИСТРИРОВАНИЕ</span><h1>{section}</h1></div><div><a href="/scan">⌗ QR Scanner</a><a className="mobileHubLink" href="/hub">В HUB ↗</a><button className="manageAvatar">BK</button></div></header><div className="manageContent"><AdminSection section={section} data={data} open={setModal} changeRole={setRoleTarget} remove={(entity,id)=>act({action:"delete",entity,id},"Запись удалена")}/></div></main>
    {modal&&<EntityModal type={modal} data={data} busy={busy} close={()=>setModal(null)} submit={(payload,msg)=>act(payload,msg)}/>} {roleTarget&&<RoleModal row={roleTarget} busy={busy} close={()=>setRoleTarget(null)} submit={(role)=>{setRoleTarget(null);void act({action:"updateRole",email:roleTarget.email,role},"Права доступа обновлены")}}/>} {notice&&<div className={`manageToast ${notice.includes("Ошибка")||notice.includes("не ")?"bad":""}`}>{notice}</div>}
  </div>;
}

function Setup({ data,busy,onSetup }: { data:Data;busy:boolean;onSetup:(form:Record<string,unknown>)=>void }) {
  const [step,setStep]=useState(1); const [values,setValues]=useState({fullName:data.name||"Бекболат Кемелбеков",groupName:"Администрация DOSTEAM"});
  if(!data.canBootstrap) return <div className="manageLoading error"><div className="brandMark"><span>!</span></div><h2>Первичная настройка закрыта</h2><p>Войдите аккаунтом владельца сайта.</p><a href="/api/auth/logout">Сменить аккаунт</a></div>;
  return <main className="setupPage"><section className="setupVisual"><div className="manageBrand"><div className="brandMark"><span>D</span></div><div><b>DOSTEAM</b><small>STUDENT HUB</small></div></div><div><span>ПЕРВЫЙ ЗАПУСК</span><h1>Создадим HUB<br/><em>с чистого листа.</em></h1><p>Сначала назначим вас главным администратором. Затем вы самостоятельно добавите помещения, клубы, студентов и первое мероприятие.</p></div><small>Все данные сохраняются в защищённой базе.</small></section><section className="setupForm"><div className="stepLine"><i className="active">1</i><span/><i className={step===2?"active":""}>2</i></div>{step===1?<><span>ШАГ 1 ИЗ 2</span><h2>Профиль владельца</h2><p>Этот аккаунт получит полный доступ к системе.</p><label>Имя администратора<input value={values.fullName} onChange={e=>setValues({...values,fullName:e.target.value})}/></label><label>Подразделение<input value={values.groupName} onChange={e=>setValues({...values,groupName:e.target.value})}/></label><label>Аккаунт<input value={data.email||""} disabled/></label><button className="primary wide" onClick={()=>setStep(2)}>Продолжить →</button></>:<><span>ШАГ 2 ИЗ 2</span><h2>Что будет создано</h2><p>Пустая система без тестовых заявок и выдуманных участников.</p><div className="setupList"><div><i>✓</i><b>Ваш Admin-профиль</b><small>Полные права управления</small></div><div><i>✓</i><b>6 уровней активности</b><small>От «Новичка» до «Legend»</small></div><div><i>✓</i><b>Чистые справочники</b><small>Клубы, события и помещения — с нуля</small></div></div><button className="primary wide" disabled={busy} onClick={()=>onSetup(values)}>{busy?"Создаём систему…":"Запустить DOSTEAM HUB"}</button><button className="backButton" onClick={()=>setStep(1)}>← Назад</button></>}</section></main>;
}

function AdminSection({section,data,open,changeRole,remove}:{section:string;data:Data;open:(x:string)=>void;changeRole:(row:Row)=>void;remove:(entity:string,id:string)=>void}) {
  if(section==="Обзор") return <Overview data={data} open={open}/>;
  const config:Record<string,{rows:Row[];action:string;label:string;entity:string;roleControl?:boolean;columns:[string,string][]}>={
    "Студенты":{rows:data.students||[],action:"student",label:"Добавить студента",entity:"",roleControl:true,columns:[["full_name","Имя"],["email","Почта"],["group_name","Группа"],["role","Роль"],["xp","XP"],["coin_balance","Coins"]]},
    "Мероприятия":{rows:data.events||[],action:"event",label:"Создать мероприятие",entity:"event",columns:[["title","Название"],["category","Категория"],["starts_at","Дата"],["capacity","Мест"],["registered","Регистраций"],["attended","Пришли"],["status","Статус"]]},
    "Клубы":{rows:data.clubs||[],action:"club",label:"Создать клуб",entity:"club",columns:[["name","Название"],["direction","Направление"],["status","Статус"],["instagram","Instagram"],["telegram","Telegram"]]},
    "Публикации":{rows:data.posts||[],action:"post",label:"Создать публикацию",entity:"post",columns:[["club_name","Клуб"],["body","Текст"],["likes","Лайки"],["comments","Комментарии"],["published_at","Дата"]]},
    "Помещения":{rows:data.rooms||[],action:"room",label:"Добавить помещение",entity:"room",columns:[["name","Название"],["capacity","Вместимость"],["location","Расположение"],["equipment_json","Оснащение"],["is_active","Доступно"]]},
    "DC Coins":{rows:data.transactions||[],action:"coins",label:"Начислить / списать",entity:"",columns:[["full_name","Студент"],["amount","Операция"],["reason","Причина"],["created_at","Дата"]]},
    "Достижения":{rows:data.achievements||[],action:"achievement",label:"Создать достижение",entity:"achievement",columns:[["name","Название"],["rule_type","Условие"],["rule_value","Значение"],["xp_reward","XP"],["coin_reward","Coins"],["is_active","Активно"]]},
    "Магазин наград":{rows:data.rewards||[],action:"reward",label:"Добавить награду",entity:"reward",columns:[["name","Название"],["cost","Стоимость DC"],["stock","Остаток"],["is_active","Активно"]]},
  }; const c=config[section];
  return <><div className="listHead"><div><h2>{section}</h2><p>{countLabel(section,c.rows.length)}</p></div><button onClick={()=>open(c.action)}>+ {c.label}</button></div>{c.rows.length?<div className="dataTable"><header>{c.columns.map(x=><span key={x[0]}>{x[1]}</span>)}{(c.entity||c.roleControl)&&<span/>}</header>{c.rows.map((row,i)=><div key={String(row.id||i)}>{c.columns.map(x=><span key={x[0]}>{formatValue(x[0],row[x[0]])}</span>)}{c.roleControl&&<button className="rowRole" onClick={()=>changeRole(row)}>Доступ</button>}{c.entity&&<button className="rowDelete" onClick={()=>remove(c.entity,String(row.id))}>×</button>}</div>)}</div>:<EmptyState section={section} action={()=>open(c.action)} label={c.label}/>}</>;
}

function Overview({data,open}:{data:Data;open:(x:string)=>void}) {
  const s=data.summary||{}; const cards=[["Студенты",s.students||0,"student"],["Активные клубы",s.clubs||0,"club"],["Мероприятия",s.events||0,"event"],["Помещения",s.rooms||0,"room"],["Выдано Coins",s.coins_issued||0,"coins"]];
  return <><div className="welcomeAdmin"><div><span>СИСТЕМА ГОТОВА К РАБОТЕ</span><h2>Начните наполнять DOSTEAM HUB</h2><p>Лучший порядок: помещения → клубы → студенты → мероприятия. Так связи создадутся без ручной возни.</p></div><div className="setupProgress"><b>{cards.filter(x=>Number(x[1])>0).length}/5</b><span>базовых разделов<br/>заполнено</span></div></div><div className="liveMetrics">{cards.map(x=><button key={String(x[0])} onClick={()=>open(String(x[2]))}><span>{icon(String(x[0]))}</span><div><small>{x[0]}</small><b>{Number(x[1]).toLocaleString("ru-RU")}</b></div><em>+</em></button>)}</div><div className="quickStart"><div className="listHead"><div><span>БЫСТРЫЙ СТАРТ</span><h2>Настройте основу</h2></div></div><div className="quickGrid"><button onClick={()=>open("room")}><i>01</i><b>Добавьте помещения</b><p>Конференц-зал, аудитории и переговорные.</p><span>Начать →</span></button><button onClick={()=>open("club")}><i>02</i><b>Создайте клубы</b><p>Назначьте направления и социальные сети.</p><span>Начать →</span></button><button onClick={()=>open("student")}><i>03</i><b>Добавьте студентов</b><p>Профили, группы и первоначальные роли.</p><span>Начать →</span></button><button onClick={()=>open("event")}><i>04</i><b>Опубликуйте событие</b><p>Откройте регистрацию и назначьте награды.</p><span>Начать →</span></button></div></div></>;
}

function EmptyState({section,action,label}:{section:string;action:()=>void;label:string}) { return <div className="adminEmpty"><div>{icon(section)}</div><h3>В разделе пока пусто</h3><p>Никаких тестовых записей. Добавьте первую настоящую.</p><button onClick={action}>+ {label}</button></div> }

function RoleModal({row,busy,close,submit}:{row:Row;busy:boolean;close:()=>void;submit:(role:string)=>void}) {
  const [role,setRole]=useState(String(row.role||"student"));
  return <div className="modalLayer" onMouseDown={close}><form className="entityModal roleModal" onSubmit={e=>{e.preventDefault();submit(role)}} onMouseDown={e=>e.stopPropagation()}><header><div><span>КОНТРОЛЬ ДОСТУПА</span><h2>{String(row.full_name||row.email)}</h2></div><button type="button" onClick={close}>×</button></header><div className="roleWarning"><b>Давайте только необходимые права</b><p>Student не видит служебные разделы. Club Manager и Event Organizer получают QR Scanner. Admin получает полный доступ ко всей системе.</p></div><div className="entityFields"><label>Роль пользователя<select value={role} onChange={e=>setRole(e.target.value)}><option value="student">Student</option><option value="club_manager">Club Manager + Scanner</option><option value="event_organizer">Event Organizer + Scanner</option><option value="admin">Admin — полный доступ</option></select></label><label>Аккаунт<input value={String(row.email||"")} disabled/></label></div><footer><button type="button" onClick={close}>Отмена</button><button className="primary" disabled={busy}>{busy?"Сохраняем…":"Изменить доступ"}</button></footer></form></div>;
}

function EntityModal({type,data,busy,close,submit}:{type:string;data:Data;busy:boolean;close:()=>void;submit:(p:Record<string,unknown>,m:string)=>void}) {
  const defs:Record<string,{title:string;action:string;success:string;fields:{name:string;label:string;type?:string;required?:boolean;options?:[string,string][];placeholder?:string;purpose?:string}[]}>= {
    room:{title:"Новое помещение",action:"createRoom",success:"Помещение добавлено",fields:[{name:"name",label:"Название",required:true,placeholder:"Конференц-зал"},{name:"capacity",label:"Вместимость",type:"number",required:true,placeholder:"100"},{name:"location",label:"Расположение",placeholder:"1 этаж"},{name:"equipment",label:"Оснащение через запятую",placeholder:"Экран, микрофоны, Wi-Fi"}]},
    club:{title:"Новый клуб",action:"createClub",success:"Клуб создан",fields:[{name:"name",label:"Название",required:true,placeholder:"EAGI Running"},{name:"direction",label:"Направление",required:true,placeholder:"Спорт и здоровье"},{name:"description",label:"Описание",placeholder:"Чем занимается клуб"},{name:"logo",label:"Логотип",type:"file",purpose:"club_logo"},{name:"instagram",label:"Instagram",placeholder:"@eagirunning"},{name:"telegram",label:"Telegram",placeholder:"t.me/eagirunning"}]},
    student:{title:"Новый студент",action:"addStudent",success:"Студент добавлен",fields:[{name:"fullName",label:"Имя и фамилия",required:true},{name:"email",label:"Почта",type:"email",required:true,placeholder:"student@eagi.kz"},{name:"groupName",label:"Группа",placeholder:"ЮТК-25"},{name:"faculty",label:"Факультет"},{name:"role",label:"Роль",type:"select",options:[["student","Student"],["club_manager","Club Manager"],["event_organizer","Event Organizer"],["admin","Admin"]]}]},
    event:{title:"Новое мероприятие",action:"createEvent",success:"Мероприятие опубликовано",fields:[{name:"title",label:"Название",required:true},{name:"category",label:"Категория",placeholder:"Спорт"},{name:"description",label:"Описание"},{name:"cover",label:"Афиша",type:"file",purpose:"event_cover"},{name:"startsAt",label:"Начало",type:"datetime-local",required:true},{name:"endsAt",label:"Окончание",type:"datetime-local",required:true},{name:"capacity",label:"Количество мест",type:"number",required:true},{name:"clubId",label:"Клуб",type:"select",options:[["","Без клуба"],...(data.clubs||[]).map(x=>[String(x.id),String(x.name)] as [string,string])]},{name:"roomId",label:"Помещение",type:"select",options:[["","Другое место"],...(data.rooms||[]).map(x=>[String(x.id),String(x.name)] as [string,string])]},{name:"placeText",label:"Дополнительный адрес"},{name:"xpReward",label:"Награда XP",type:"number",placeholder:"40"},{name:"coinReward",label:"Награда DC Coins",type:"number",placeholder:"10"}]},
    post:{title:"Новая публикация",action:"createPost",success:"Публикация вышла в ленте",fields:[{name:"clubId",label:"Клуб",type:"select",required:true,options:(data.clubs||[]).map(x=>[String(x.id),String(x.name)] as [string,string])},{name:"body",label:"Текст публикации",required:true,placeholder:"Расскажите о новости клуба"},{name:"media",label:"Фото или видео",type:"file",purpose:"post_media"},{name:"linkUrl",label:"Ссылка",placeholder:"https://..."},{name:"tags",label:"Теги",placeholder:"#спорт #eagi"}]},
    coins:{title:"Операция с DC Coins",action:"adjustCoins",success:"Баланс обновлён",fields:[{name:"email",label:"Почта студента",type:"email",required:true},{name:"amount",label:"Количество (+ начислить, − списать)",type:"number",required:true,placeholder:"30"},{name:"reason",label:"Причина",required:true,placeholder:"Волонтёрство на EAGI CUP"}]},
    achievement:{title:"Новое достижение",action:"createAchievement",success:"Достижение создано",fields:[{name:"name",label:"Название",required:true,placeholder:"Первые шаги"},{name:"description",label:"Описание"},{name:"category",label:"Категория",placeholder:"Активность"},{name:"ruleType",label:"Условие",type:"select",options:[["events_attended","Посещено мероприятий"],["clubs_joined","Вступил в клубы"],["volunteer_count","Волонтёрства"],["events_organized","Организовано событий"],["coins_earned","Заработано Coins"]]},{name:"ruleValue",label:"Целевое значение",type:"number",required:true,placeholder:"10"},{name:"xpReward",label:"Награда XP",type:"number",placeholder:"100"},{name:"coinReward",label:"Награда Coins",type:"number",placeholder:"25"}]},
    reward:{title:"Награда магазина",action:"createReward",success:"Награда добавлена в магазин",fields:[{name:"name",label:"Название",required:true,placeholder:"Футболка DOSTEAM"},{name:"description",label:"Описание",placeholder:"Размеры и условия получения"},{name:"cost",label:"Стоимость в DC Coins",type:"number",required:true,placeholder:"500"},{name:"stock",label:"Количество в наличии",type:"number",required:true,placeholder:"20"},{name:"image",label:"Изображение",type:"file",purpose:"reward_image"}]},
  }; const d=defs[type]; if(!d)return null;
  const send=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);const values=Object.fromEntries(form.entries()) as Record<string,unknown>;for(const f of d.fields.filter(x=>x.type==="file")){const file=form.get(f.name);delete values[f.name];if(file instanceof File&&file.size){const upload=new FormData();upload.set("file",file);upload.set("purpose",f.purpose||"post_media");const response=await fetch("/api/uploads",{method:"POST",body:upload});const result=await response.json();if(!response.ok)throw new Error(result.error||"Не удалось загрузить файл");if(f.name==="logo")values.logoUrl=result.url;else if(f.name==="cover")values.coverUrl=result.url;else if(f.name==="image")values.imageUrl=result.url;else{values.mediaUrl=result.url;values.mediaType=result.contentType}}}submit({action:d.action,...values},d.success)};
  return <div className="modalLayer" onMouseDown={close}><form className="entityModal" onSubmit={send} onMouseDown={e=>e.stopPropagation()}><header><div><span>DOSTEAM CONTROL</span><h2>{d.title}</h2></div><button type="button" onClick={close}>×</button></header><div className="entityFields">{d.fields.map(f=><label key={f.name}>{f.label}{f.type==="select"?<select name={f.name} required={f.required}>{f.options?.map(o=><option key={o[0]} value={o[0]}>{o[1]}</option>)}</select>:<input name={f.name} type={f.type||"text"} required={f.required} placeholder={f.placeholder} accept={f.type==="file"?"image/png,image/jpeg,image/webp,image/gif,video/mp4":undefined}/>}</label>)}</div><footer><button type="button" onClick={close}>Отмена</button><button className="primary" disabled={busy}>{busy?"Сохраняем…":"Сохранить"}</button></footer></form></div>;
}

function icon(x:string){if(x.includes("Студ"))return"♙";if(x.includes("Клуб"))return"◎";if(x.includes("Публик"))return"◫";if(x.includes("Мер"))return"◇";if(x.includes("Пом"))return"▦";if(x.includes("Coin"))return"◉";if(x.includes("Дост"))return"✦";if(x.includes("Магаз"))return"▣";return"⌂"}
function countLabel(section:string,n:number){return `${n} ${section==="Студенты"?"профилей":section==="DC Coins"?"операций":"записей"}`}
function formatValue(key:string,v:Row[string]){if(v===null||v==="")return"—";if(key.endsWith("_at")&&typeof v==="number")return new Date(v).toLocaleString("ru-RU",{dateStyle:"short",timeStyle:"short"});if(key==="equipment_json")try{return(JSON.parse(String(v)) as string[]).join(", ")||"—"}catch{return String(v)}if(typeof v==="boolean"||key==="is_active")return Number(v)?"Да":"Нет";if(key==="amount")return <b className={Number(v)>=0?"positive":"negative"}>{Number(v)>0?"+":""}{v}</b>;return String(v)}
