import { apiJson, cleanText, requireHubUser } from "../_lib";

export const dynamic = "force-dynamic";

export async function POST(request:Request) {
  const ctx=await requireHubUser(["admin","event_organizer","club_manager"]); if("error" in ctx)return ctx.error;
  const body=await request.json().catch(()=>({})) as Record<string,unknown>; const code=cleanText(body.code,80).toUpperCase(); if(!code)return apiJson({error:"Введите код билета"},400);
  const ticket=await ctx.db.prepare("SELECT r.id registration_id,r.status,r.user_id,e.id event_id,e.title,e.organizer_id,e.club_id,e.starts_at,e.ends_at,e.xp_reward,e.coin_reward,p.full_name,p.xp,p.coin_balance,p.level_id FROM registrations r JOIN events e ON e.id=r.event_id JOIN profiles p ON p.user_id=r.user_id WHERE r.ticket_code=?").bind(code).first<{registration_id:string;status:string;user_id:string;event_id:string;title:string;organizer_id:string;club_id:string|null;starts_at:number;ends_at:number;xp_reward:number;coin_reward:number;full_name:string;xp:number;coin_balance:number;level_id:number|null}>();
  if(!ticket)return apiJson({error:"Билет не найден"},404);
  if(ctx.user.role!=="admin"&&ticket.organizer_id!==ctx.user.id){const manager=ticket.club_id?await ctx.db.prepare("SELECT 1 ok FROM club_memberships WHERE club_id=? AND user_id=? AND role IN ('manager','moderator') AND status='approved'").bind(ticket.club_id,ctx.user.id).first():null;if(!manager)return apiJson({error:"Вы не организатор этого события"},403)}
  if(ticket.status==="attended")return apiJson({ok:true,already:true,name:ticket.full_name,event:ticket.title,xp:ticket.xp_reward,coins:ticket.coin_reward});
  if(ticket.status!=="registered")return apiJson({error:`Билет имеет статус ${ticket.status}`},409);
  const now=Date.now(); const newXp=ticket.xp+ticket.xp_reward,newBalance=ticket.coin_balance+ticket.coin_reward;
  try{await ctx.db.batch([ctx.db.prepare("UPDATE registrations SET status='attended',attended_at=?,scanned_by=? WHERE id=? AND status='registered'").bind(now,ctx.user.id,ticket.registration_id),ctx.db.prepare("UPDATE profiles SET xp=?,coin_balance=? WHERE user_id=?").bind(newXp,newBalance,ticket.user_id),ctx.db.prepare("INSERT INTO xp_transactions (id,user_id,amount,reason,source_type,source_id,created_at,created_by) VALUES (?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),ticket.user_id,ticket.xp_reward,`Посещение: ${ticket.title}`,"event_attendance",ticket.event_id,now,ctx.user.id),ctx.db.prepare("INSERT INTO coin_transactions (id,user_id,amount,balance_after,reason,source_type,source_id,created_at,created_by) VALUES (?,?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),ticket.user_id,ticket.coin_reward,newBalance,`Посещение: ${ticket.title}`,"event_attendance",ticket.event_id,now,ctx.user.id),ctx.db.prepare("INSERT INTO notifications (id,user_id,type,title,body,action_url,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),ticket.user_id,"attendance","Посещение подтверждено",`+${ticket.xp_reward} XP · +${ticket.coin_reward} DC за ${ticket.title}`,"/join",now)]);}catch{return apiJson({ok:true,already:true,name:ticket.full_name,event:ticket.title,xp:ticket.xp_reward,coins:ticket.coin_reward})}
  const level=await ctx.db.prepare("SELECT id,name_ru FROM levels WHERE is_active=1 AND min_xp<=? ORDER BY min_xp DESC LIMIT 1").bind(newXp).first<{id:number;name_ru:string}>(); if(level&&level.id!==ticket.level_id){await ctx.db.batch([ctx.db.prepare("UPDATE profiles SET level_id=? WHERE user_id=?").bind(level.id,ticket.user_id),ctx.db.prepare("INSERT INTO notifications (id,user_id,type,title,body,action_url,created_at) VALUES (?,?,?,?,?,?,?)").bind(crypto.randomUUID(),ticket.user_id,"level_up","Новый уровень",`Теперь ваш уровень — ${level.name_ru}`,"/join",now)])}
  return apiJson({ok:true,already:false,name:ticket.full_name,event:ticket.title,xp:ticket.xp_reward,coins:ticket.coin_reward,level:level?.name_ru});
}
