"use client";

import { FormEvent,useCallback,useEffect,useState } from "react";
type Row=Record<string,string|number|null>; type Member={onboarding?:boolean;error?:string;profile?:Row;tickets?:Row[];memberships?:Row[];follows?:Row[];notifications?:Row[]};

export default function MemberClient({authName,authEmail}:{authName:string;authEmail:string}){
  const [data,setData]=useState<Member|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [ticket,setTicket]=useState<Row|null>(null);
  const load=useCallback(()=>fetch("/api/member").then(r=>r.json()).then(setData).catch(()=>setData({error:"Не удалось загрузить профиль"})),[]);useEffect(()=>{void load()},[load]);
  const onboard=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();setBusy(true);const fd=new FormData(e.currentTarget);let avatarUrl="";const file=fd.get("avatar");if(file instanceof File&&file.size){const up=new FormData();up.set("file",file);up.set("purpose","avatar");const ur=await fetch("/api/uploads",{method:"POST",body:up});if(ur.ok)avatarUrl=(await ur.json()).url}const payload=Object.fromEntries(fd.entries());delete payload.avatar;const r=await fetch("/api/member",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"onboard",...payload,avatarUrl,interests:fd.getAll("interests")})});const result=await r.json();if(!r.ok)setMessage(result.error);else await load();setBusy(false)};
  if(!data)return <div className="memberLoading"><div className="brandMark"><span>D</span></div><p>Открываем твой HUB…</p></div>;
  if(data.onboarding)return <main className="onboardPage"><section><a href="/join" className="manageBrand"><div className="brandMark"><span>D</span></div><div><b>DOSTEAM</b><small>STUDENT HUB</small></div></a><div><span>ЦИФРОВОЙ STUDENT ID</span><h1>Создай свой профиль<br/>в DOSTEAM HUB.</h1><p>После регистрации ты сможешь вступать в клубы, получать QR-билеты, XP, DC Coins и достижения.</p></div><small>Вход подтверждён: {authEmail}</small></section><form onSubmit={onboard}><span>РЕГИСТРАЦИЯ СТУДЕНТА</span><h2>Расскажи о себе</h2><p>Поля можно изменить позже в профиле.</p><label>Фотография<input type="file" name="avatar" accept="image/png,image/jpeg,image/webp"/></label><div className="formPair"><label>Имя и фамилия<input name="fullName" defaultValue={authName} required/></label><label>Студенческий ID<input name="studentId" placeholder="EAGI-2026-001" required/></label><label>Группа<input name="groupName" placeholder="ЮТК-25" required/></label><label>Курс<select name="course"><option>1</option><option>2</option><option>3</option><option>4</option></select></label></div><label>Факультет<input name="faculty" placeholder="Юридический факультет"/></label><label>Коротко о себе<textarea name="bio" placeholder="Интересы, проекты, цели…"/></label><fieldset><legend>Интересы</legend>{["Спорт","Бизнес","Дебаты","Медиа","Волонтёрство","Культура"].map(x=><label key={x}><input type="checkbox" name="interests" value={x}/>{x}</label>)}</fieldset>{message&&<p className="formError">{message}</p>}<button className="primary wide" disabled={busy}>{busy?"Создаём профиль…":"Создать мой HUB →"}</button></form></main>;
  const p=data.profile||{};return <main className="memberPage"><header><a href="/join" className="manageBrand"><div className="brandMark"><span>D</span></div><div><b>DOSTEAM</b><small>MY HUB</small></div></a><nav><a href="/hub">Открыть HUB</a><a href="#tickets">Билеты</a><a href="#clubs">Клубы</a><a href="/api/auth/logout">Выйти</a></nav></header><section className="memberHero"><div className="memberAvatar">{p.avatar_url?<img src={String(p.avatar_url)} alt=""/>:String(p.full_name||"S").split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><span>ЦИФРОВОЙ ПРОФИЛЬ</span><h1>{p.full_name}</h1><p>{p.group_name} · {p.faculty||"ЕАГИ"}</p><div><b>Level · {p.level_name||"Новичок"}</b><b>{p.xp||0} XP</b><b>{p.coin_balance||0} DC</b></div></div></section><div className="memberGrid"><section id="tickets" className="memberCard wideCard"><header><div><span>МОИ СОБЫТИЯ</span><h2>Электронные билеты</h2></div><a href="/hub">Найти мероприятие →</a></header>{(data.tickets||[]).length?(data.tickets||[]).map(t=><button className="ticketRow" key={String(t.ticket_code)} onClick={()=>setTicket(t)}><div><b>{new Date(Number(t.starts_at)).getDate()}</b><span>{new Date(Number(t.starts_at)).toLocaleString("ru-RU",{month:"short"})}</span></div><p><b>{t.title}</b><span>{new Date(Number(t.starts_at)).toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"})} · {t.place_text||"ЕАГИ"}</span></p><em className={String(t.status)}>{t.status}</em><strong>QR →</strong></button>):<EmptyMini title="Билетов пока нет" text="Зарегистрируйся на первое мероприятие."/>}</section><section id="clubs" className="memberCard"><header><div><span>МОИ КЛУБЫ</span><h2>Участие</h2></div></header>{(data.memberships||[]).map(m=><div className="memberClub" key={String(m.id)}><span>◎</span><div><b>{m.name}</b><small>{m.direction}</small></div><em>{m.status}</em></div>)}{!(data.memberships||[]).length&&<EmptyMini title="Заявок пока нет" text="Выбери клуб и отправь заявку."/>}</section><section className="memberCard"><header><div><span>УВЕДОМЛЕНИЯ</span><h2>Последнее</h2></div></header>{(data.notifications||[]).slice(0,5).map(n=><div className="memberNotice" key={String(n.id)}><span>✦</span><div><b>{n.title}</b><small>{n.body}</small></div></div>)}{!(data.notifications||[]).length&&<EmptyMini title="Пока тихо" text="Здесь появятся важные обновления."/>}</section></div>{ticket&&<div className="modalLayer" onMouseDown={()=>setTicket(null)}><div className="realTicket" onMouseDown={e=>e.stopPropagation()}><button onClick={()=>setTicket(null)}>×</button><span>DOSTEAM HUB · E-TICKET</span><h2>{ticket.title}</h2><img src={`/api/ticket/${ticket.ticket_code}`} alt="QR-код билета"/><b>{ticket.ticket_code}</b><p>{p.full_name} · {p.group_name}</p><small>Покажите QR-код организатору при входе</small></div></div>}</main>}
function EmptyMini({title,text}:{title:string;text:string}){return <div className="emptyMini"><i>＋</i><b>{title}</b><span>{text}</span></div>}
