"use client";

import { useEffect, useState } from "react";
import { Avatar, type HubIdentity, type View } from "./hub";

type Go = (view: View) => void;

type CatalogEvent = { id:string|number; date:string; month:string; title:string; time:string; place:string; club:string; seats:number; total:number; reward:string; category:string; color:string; ticketCode?:string };
type ClubCard = { id?:string; name:string; type:string; description:string; followers:string|number; members:number; posts:number; letters:string; color:string; logoUrl?:string; instagram?:string;telegram?:string };

type LiveData = { events: Record<string, unknown>[]; clubs: Record<string, unknown>[]; rooms: Record<string, unknown>[]; leaderboard:Record<string,unknown>[]; summary: Record<string, unknown> };
function useLiveData() {
  const [data,setData]=useState<LiveData|null>(null);
  useEffect(()=>{fetch("/api/public").then(r=>r.json()).then(setData).catch(()=>setData({events:[],clubs:[],rooms:[],leaderboard:[],summary:{}}))},[]);
  return data;
}

export default function RoutedView({ view, go, flash, identity }: { view: View; go: Go; flash: (message: string) => void; identity:HubIdentity }) {
  if (view === "events") return <EventsView flash={flash} />;
  if (view === "clubs") return <ClubsView flash={flash} />;
  if (view === "feed") return <FeedView flash={flash} />;
  if (view === "leaderboard") return <LeaderboardView identity={identity} />;
  if (view === "rooms") return <RoomsView flash={flash} />;
  if (view === "achievements") return <AchievementsView />;
  if (view === "rewards") return <RewardsView identity={identity} />;
  if (view === "profile") return <ProfileView go={go} />;
  if (view === "admin") return <AdminView flash={flash} />;
  return null;
}

function PageIntro({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: React.ReactNode }) {
  return <div className="pageIntro"><div><span>{eyebrow}</span><h2>{title}</h2><p>{text}</p></div>{action}</div>;
}

function EventsView({ flash }: { flash: (message: string) => void }) {
  const live=useLiveData(); const [filter,setFilter]=useState("Все"); const [ticket,setTicket]=useState<CatalogEvent|null>(null);
  const source=(live?.events||[]).map((e,i)=>{const d=new Date(Number(e.starts_at));return{id:String(e.id),date:String(d.getDate()).padStart(2,"0"),month:d.toLocaleString("ru-RU",{month:"short"}).replace(".",""),title:String(e.title),time:d.toLocaleTimeString("ru-RU",{hour:"2-digit",minute:"2-digit"}),place:String(e.place_text||"ЕАГИ"),club:String(e.club_name||"DOSTEAM"),seats:Math.max(0,Number(e.capacity)-Number(e.registered||0)),total:Number(e.capacity),reward:`+${Number(e.xp_reward||0)} XP · +${Number(e.coin_reward||0)} DC`,category:String(e.category||"Другое"),color:["eventYellow","eventBlue","eventOrange","eventPurple"][i%4]}});
  const filtered=filter==="Все"?source:source.filter(e=>e.category===filter);
  const register=async(event:CatalogEvent)=>{const r=await fetch("/api/member",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"registerEvent",eventId:event.id,source:"hub"})});const result=await r.json();if(r.status===401||result.onboarding){window.location.assign("/join");return}if(!r.ok){flash(result.error||"Не удалось зарегистрироваться");return}setTicket({...event,ticketCode:result.ticketCode})};
  return <div className="pageContent"><PageIntro eyebrow="УЧАСТВУЙ И РАЗВИВАЙСЯ" title="Мероприятия" text="Здесь отображаются только опубликованные организаторами события."/>
    <div className="filterBar">{["Все","Спорт","Бизнес","Образование","Культура","Волонтёрство"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}<div className="filterSearch">⌕ <input placeholder="Поиск событий"/></div></div>
    {!live?<LiveLoading/>:filtered.length?<div className="eventCatalog">{filtered.map((event)=><article className="eventTile" key={event.id}><div className={`eventPoster ${event.color}`}><span>{event.category}</span><div className="posterDate"><b>{event.date}</b><small>{event.month}</small></div><em>DOSTEAM<br/>HUB</em></div><div className="eventTileBody"><span>{event.club}</span><h3>{event.title}</h3><p>◷ {event.time} &nbsp; · &nbsp; ⌖ {event.place}</p><div className="capacity"><div><i style={{width:`${100-event.seats/event.total*100}%`}}/></div><small>{event.seats} свободно из {event.total}</small></div><div className="eventTileFoot"><b>{event.reward}</b><button onClick={()=>register(event)}>Зарегистрироваться</button></div></div></article>)}</div>:<LiveEmpty title="Пока нет опубликованных мероприятий" text="Как только организатор создаст событие, оно появится здесь."/>}
    {ticket&&<div className="modalLayer" onMouseDown={()=>setTicket(null)}><div className="ticketModal" onMouseDown={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setTicket(null)}>×</button><div className="ticketBrand">DOSTEAM <span>HUB</span></div><p>ЭЛЕКТРОННЫЙ БИЛЕТ</p><h3>{ticket.title}</h3><div className="ticketMeta"><span><small>ДАТА И ВРЕМЯ</small>{ticket.date} {ticket.month}, {ticket.time}</span><span><small>МЕСТО</small>{ticket.place}</span><span><small>СТАТУС</small><b>REGISTERED</b></span><span><small>КОД</small>{ticket.ticketCode}</span></div>{ticket.ticketCode&&<img className="realQr" src={`/api/ticket/${ticket.ticketCode}`} alt="QR-код билета"/>}<small className="ticketCode">{ticket.ticketCode}</small><button className="primary wide" onClick={()=>window.location.assign("/join")}>Открыть мои билеты</button></div></div>}
  </div>;
}

function ClubsView({ flash }: { flash: (message: string) => void }) {
  const live=useLiveData(); const [following,setFollowing]=useState<string[]>([]); const [selected,setSelected]=useState<ClubCard|null>(null);
  const source=(live?.clubs||[]).map((c,i)=>({id:String(c.id),name:String(c.name),type:String(c.direction||"Направление не указано"),description:String(c.description||"Описание клуба пока не добавлено."),followers:Number(c.followers||0),members:Number(c.members||0),posts:Number(c.posts||0),letters:String(c.name).split(/\s+/).map(x=>x[0]).join("").slice(0,2).toUpperCase(),color:["#111","#2672ff","#7442d6","#e78b27","#16956c"][i%5],logoUrl:c.logo_url?String(c.logo_url):undefined,instagram:String(c.instagram||""),telegram:String(c.telegram||"")}));
  const memberAction=async(club:ClubCard,action:"followClub"|"joinClub")=>{const r=await fetch("/api/member",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,clubId:club.id})});const result=await r.json();if(r.status===401||result.onboarding){window.location.assign("/join");return}if(!r.ok){flash(result.error||"Не удалось выполнить действие");return}if(action==="followClub")setFollowing(x=>result.following?[...x.filter(n=>n!==club.name),club.name]:x.filter(n=>n!==club.name));else flash("Заявка отправлена — на рассмотрении")};
  return <div className="pageContent"><PageIntro eyebrow="НАЙДИ СВОИХ" title="Студенческие клубы" text="Здесь отображаются только одобренные и активные клубы ЕАГИ."/>
    {source[0]&&<div className="clubHero"><div><span>АКТИВНЫЙ КЛУБ</span><h3>{source[0].name}</h3><p>{source[0].description}</p><button onClick={()=>setSelected(source[0])}>Открыть клуб →</button></div><strong>JOIN<br/><i>THE</i><br/>TEAM.</strong></div>}
    <div className="catalogHead"><h3>Все клубы <span>{source.length}</span></h3><div className="filterSearch">⌕ <input placeholder="Найти клуб"/></div></div>
    {!live?<LiveLoading/>:source.length?<div className="clubCatalog">{source.map(club=><article key={club.name}><div className="clubCover" style={{background:club.color}}>{club.logoUrl?<img src={club.logoUrl} alt={`Логотип ${club.name}`}/>:<span>{club.letters}</span>}</div><div className="clubBody"><h3>{club.name}</h3><p>{club.type}</p><div className="clubNumbers"><span><b>{club.followers}</b> подписчиков</span><span><b>{club.members}</b> участников</span><span><b>{club.posts}</b> постов</span></div><div className="clubActions"><button className={following.includes(club.name)?"following":""} onClick={()=>memberAction(club,"followClub")}>{following.includes(club.name)?"✓ Подписан":"Подписаться"}</button><button onClick={()=>setSelected(club)}>Вступить</button></div></div></article>)}</div>:<LiveEmpty title="Клубов пока нет" text="Одобренные клубы появятся здесь."/>}
    {selected&&<div className="modalLayer" onMouseDown={()=>setSelected(null)}><div className="clubProfileModal" onMouseDown={e=>e.stopPropagation()}><button className="modalClose" onClick={()=>setSelected(null)}>×</button><div className="clubProfileTop" style={{background:selected.color}}><div className="bigClubLogo">{selected.logoUrl?<img src={selected.logoUrl} alt=""/>:selected.letters}</div><span>{selected.type}</span></div><h2>{selected.name}</h2><p>{selected.description}</p><div className="clubProfileStats"><span><b>{selected.followers}</b>Подписчиков</span><span><b>{selected.members}</b>Участников</span><span><b>{selected.posts}</b>Постов</span></div>{selected.instagram&&<p>Instagram: {selected.instagram}</p>}{selected.telegram&&<p>Telegram: {selected.telegram}</p>}<button className="primary wide" onClick={()=>{void memberAction(selected,"joinClub");setSelected(null)}}>Отправить заявку на вступление</button></div></div>}
  </div>;
}

function FeedView({ flash }: { flash: (message: string) => void }) {
  const [tab,setTab]=useState("Подписки"); const [posts,setPosts]=useState<Record<string,unknown>[]|null>(null); const [commentFor,setCommentFor]=useState(""); const [comment,setComment]=useState(""); const [commentRows,setCommentRows]=useState<Record<string,Record<string,unknown>[]>>({});
  const load=()=>fetch(`/api/social?feed=${tab==="Подписки"?"following":"for-you"}`).then(r=>r.json()).then(x=>setPosts(x.posts||[])).catch(()=>setPosts([]));
  useEffect(()=>{setPosts(null);void load()},[tab]);
  const act=async(payload:Record<string,unknown>)=>{const r=await fetch("/api/social",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await r.json();if(r.status===401||result.onboarding){window.location.assign("/join");return false}if(!r.ok){flash(result.error||"Не удалось выполнить действие");return false}await load();return true};
  const openComments=async(id:string)=>{if(commentFor===id){setCommentFor("");return}setCommentFor(id);const r=await fetch(`/api/social?postId=${encodeURIComponent(id)}`);const result=await r.json();setCommentRows(x=>({...x,[id]:result.comments||[]}))};
  return <div className="pageContent feedPage"><PageIntro eyebrow="ВСЁ ВАЖНОЕ — ЗДЕСЬ" title="Моя лента" text="Новости клубов, события и рекомендации на основе твоих интересов."/>
    <div className="feedTabs"><button className={tab==="Подписки"?"active":""} onClick={()=>setTab("Подписки")}>Подписки</button><button className={tab==="Для вас"?"active":""} onClick={()=>setTab("Для вас")}>Для вас</button></div>
    <div className="feedLayout"><div className="posts">{posts===null?<LiveLoading/>:posts.length?posts.map((post,i)=>{const media=firstMedia(post.media_json);const id=String(post.id);const color=["#111","#216df3","#7442d6","#d27d22"][i%4];return <article className="post" key={id}><header><div className="clubLogo" style={{background:color}}>{String(post.club_name).split(/\s+/).map(x=>x[0]).join("").slice(0,2)}</div><div><b>{String(post.club_name)}</b><span>{new Date(Number(post.published_at)).toLocaleString("ru-RU")}</span></div><button>•••</button></header><p>{String(post.body)}</p>{media?<div className="postMedia">{media.type.startsWith("video/")?<video src={media.url} controls/>:<img src={media.url} alt="Публикация клуба"/>}</div>:<div className="postVisual" style={{background:color}}><strong>{String(post.club_name).toUpperCase()}</strong><strong>DOSTEAM HUB</strong></div>}<footer><button className={Number(post.liked)?"liked":""} onClick={()=>act({action:"react",type:"like",postId:id})}>♥ {Number(post.likes||0)}</button><button onClick={()=>openComments(id)}>◯ {Number(post.comments||0)}</button><button onClick={()=>{void navigator.clipboard?.writeText(`${location.origin}/?post=${id}`);flash("Ссылка скопирована")}}>↗ Поделиться</button><button className="save" onClick={()=>act({action:"react",type:"save",postId:id})}>{Number(post.saved)?"▣":"▢"}</button></footer>{commentFor===id&&<div className="commentArea"><div className="commentList">{(commentRows[id]||[]).map(c=><div key={String(c.id)}><span>{String(c.full_name).split(" ").map(x=>x[0]).slice(0,2).join("")}</span><p><b>{String(c.full_name)}</b>{String(c.body)}</p></div>)}</div><div className="commentComposer"><input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Написать комментарий…"/><button onClick={async()=>{if(await act({action:"comment",postId:id,body:comment})){setComment("");await openComments(id);await openComments(id);flash("Комментарий опубликован")}}}>Отправить</button></div></div>}</article>}):<LiveEmpty title={tab==="Подписки"?"Лента подписок пока пустая":"Публикаций пока нет"} text="Создайте первую публикацию клуба в Admin Panel."/>}</div>
      <aside className="feedAside"><div className="asideCard"><span>ТВОЙ ПРОФИЛЬ</span><h3>Присоединяйся к HUB</h3><div className="suggestLogo">ID</div><b>Digital Student ID</b><p>Получай билеты, XP, Coins и достижения за реальную активность.</p><button onClick={()=>window.location.assign("/join")}>Открыть мой HUB</button></div><div className="asideCard compact"><span>ДЛЯ ОРГАНИЗАТОРОВ</span><h3>QR Scanner</h3><p>Фиксируй посещаемость в один клик.</p><button onClick={()=>window.location.assign("/scan")}>Открыть →</button></div></aside>
    </div>
  </div>;
}

function LeaderboardView({identity}:{identity:HubIdentity}) {
  const live=useLiveData();
  const rows=live?.leaderboard||[];
  const podium=rows.slice(0,3);
  const initials=(name:unknown)=>String(name||"S").split(/\s+/).filter(Boolean).map(x=>x[0]).slice(0,2).join("").toUpperCase();
  return <div className="pageContent"><PageIntro eyebrow="АКТИВНОСТЬ, КОТОРАЯ ВИДНА" title="Рейтинг студентов" text="Здесь только реальные профили. Место определяется количеством подтверждённого XP."/>
    <div className="rankFilters"><div><button className="active">Общий рейтинг</button></div><select defaultValue="all" aria-label="Период рейтинга"><option value="all">За всё время</option></select></div>
    {!live?<LiveLoading/>:rows.length?<><div className="podium">{podium.map((row,index)=><div className={`podiumPerson ${index===0?"first":index===1?"second":"third"}`} key={String(row.user_id)}>{index===0&&<div className="crown">♛</div>}<Avatar text={initials(row.full_name)} imageUrl={row.avatar_url?String(row.avatar_url):null}/><i>{index+1}</i><b>{String(row.full_name)}</b><span>{Number(row.xp||0).toLocaleString("ru-RU")} XP</span></div>)}</div>
    <section className="rankTable"><header><span>МЕСТО</span><span>СТУДЕНТ</span><span>УРОВЕНЬ</span><span>ДОСТИЖЕНИЯ</span><span>XP</span></header>{rows.map((row,index)=><div className={String(row.user_id)===identity.userId?"myRank":""} key={String(row.user_id)}><strong>{index+1}</strong><span className="rankStudent"><Avatar text={initials(row.full_name)} imageUrl={row.avatar_url?String(row.avatar_url):null} small/><b>{String(row.full_name)}{String(row.user_id)===identity.userId&&<i> ВЫ</i>}<small>{String(row.group_name||"ЕАГИ")}</small></b></span><span><em>{String(row.level_name||"Новичок")}</em></span><span>{Number(row.achievements||0)}</span><b>{Number(row.xp||0).toLocaleString("ru-RU")}</b></div>)}</section></>:<LiveEmpty title="Рейтинг пока пуст" text="Он появится, когда студенты заполнят публичные профили."/>}
  </div>;
}

function RoomsView({ flash }: { flash: (message: string) => void }) {
  const live=useLiveData(); const rooms=(live?.rooms||[]).map(r=>({name:String(r.name),cap:Number(r.capacity),equip:(()=>{try{return(JSON.parse(String(r.equipment_json)) as string[]).join(" · ")}catch{return""}})(),busy:0})); const [selected,setSelected]=useState(""); const current=selected||rooms[0]?.name||"Помещение";
  return <div className="pageContent"><PageIntro eyebrow="ПЛАНИРУЙ БЕЗ НАКЛАДОК" title="Помещения" text="Здесь отображаются реальные доступные помещения ЕАГИ."/>
    {!live?<LiveLoading/>:rooms.length?<div className="roomLayout"><div className="roomList">{rooms.map(r=><button className={current===r.name?"active":""} onClick={()=>setSelected(r.name)} key={r.name}><div className="roomIcon">▦</div><div><b>{r.name}</b><span>До {r.cap} человек · {r.equip||"Оснащение не указано"}</span></div><em>Активно</em></button>)}</div><section className="scheduleCard"><header><div><span>ВЫБРАНО ПОМЕЩЕНИЕ</span><h3>{current}</h3></div></header><div className="liveState compact"><i>▦</i><h3>Расписание пока не опубликовано</h3><p>Свободные интервалы появятся после подключения реальных заявок на бронирование.</p></div></section></div>:<LiveEmpty title="Помещения не добавлены" text="Доступные помещения появятся здесь после добавления администратором."/>}
  </div>;
}

function firstMedia(value:unknown){try{const list=JSON.parse(String(value||"[]")) as (string|{url:string;type:string})[];const first=list[0];return typeof first==="string"?{url:first,type:"image/jpeg"}:first||null}catch{return null}}
function LiveLoading(){return <div className="liveState"><i>···</i><p>Загружаем данные HUB</p></div>}
function LiveEmpty({title,text}:{title:string;text:string}){return <div className="liveState"><i>＋</i><h3>{title}</h3><p>{text}</p></div>}

type MemberHubData={transactions?:Record<string,unknown>[];achievements?:Record<string,unknown>[];rewards?:Record<string,unknown>[];stats?:Record<string,unknown>};
function useMemberData(){const [data,setData]=useState<MemberHubData|null>(null);useEffect(()=>{fetch("/api/member").then(r=>r.json()).then(setData).catch(()=>setData({transactions:[],achievements:[],rewards:[],stats:{}}))},[]);return data}

function AchievementsView(){
  const member=useMemberData();const rows=member?.achievements||[];
  return <div className="pageContent"><PageIntro eyebrow="ЦИФРОВОЙ ПРОГРЕСС" title="Достижения" text="Достижения — это значки за выполненные условия. Они остаются в профиле и могут давать XP или DC Coins."/>
    {!member?<LiveLoading/>:rows.length?<div className="achievementCatalog">{rows.map(row=>{const unlocked=Boolean(row.unlocked_at);const progress=Number(row.progress||0),target=Math.max(1,Number(row.rule_value||1));return <article className={unlocked?"unlocked":"locked"} key={String(row.id)}><div className="achievementIcon">{String(row.icon||"✦")}</div><span>{String(row.category||"Активность")}</span><h3>{String(row.name)}</h3><p>{String(row.description||"Описание пока не добавлено")}</p><div className="achievementProgress"><i style={{width:`${Math.min(100,progress/target*100)}%`}}/></div><small>{unlocked?`Получено ${new Date(Number(row.unlocked_at)).toLocaleDateString("ru-RU")}`:`Прогресс: ${progress} из ${target}`}</small><footer><b>+{Number(row.xp_reward||0)} XP</b><b>+{Number(row.coin_reward||0)} DC</b></footer></article>})}</div>:<LiveEmpty title="Достижений пока нет" text="Администратор ещё не создал условия достижений."/>}
  </div>;
}

function RewardsView({identity}:{identity:HubIdentity}) {
  const member=useMemberData();const transactions=member?.transactions||[];const rewards=member?.rewards||[];
  const monthStart=new Date();monthStart.setDate(1);monthStart.setHours(0,0,0,0);const earnedThisMonth=transactions.filter(t=>Number(t.amount)>0&&Number(t.created_at)>=monthStart.getTime()).reduce((sum,t)=>sum+Number(t.amount||0),0);
  return <div className="pageContent"><PageIntro eyebrow="ВНУТРЕННЯЯ ВАЛЮТА HUB" title="DC Coins" text="DC Coins можно заработать за подтверждённую активность и потратить на реальные предложения. XP при этом не расходуется."/>
    <div className="walletHero"><div><span>ТЕКУЩИЙ БАЛАНС</span><h2>{identity.coins.toLocaleString("ru-RU")} <small>DC</small></h2><p>+{earnedThisMonth.toLocaleString("ru-RU")} DC в этом месяце</p></div><div className="coinBig">D</div></div>
    <div className="rewardLayout"><section className="sectionCard"><div className="sectionHead"><div><span>ИСТОРИЯ</span><h3>Операции</h3></div></div>{!member?<LiveLoading/>:transactions.length?transactions.map(t=><div className="transaction" key={String(t.id)}><span className={Number(t.amount)>=0?"plus":"minus"}>{Number(t.amount)>0?"+":""}{Number(t.amount)}</span><div><b>{String(t.reason||"Операция DC Coins")}</b><small>{new Date(Number(t.created_at)).toLocaleDateString("ru-RU")} · Баланс {Number(t.balance_after||0)} DC</small></div><em>DC</em></div>):<div className="emptyMini"><b>Операций пока нет</b><span>Начисления и списания появятся после подтверждённой активности.</span></div>}</section><section className="sectionCard currencyGuide"><div className="sectionHead"><div><span>НЕ ПУТАТЬ</span><h3>XP и DC Coins</h3></div></div><div><b>XP</b><p>Опыт для уровня и рейтинга. XP нельзя потратить.</p></div><div><b>DC Coins</b><p>Валюта HUB. Её можно начислять и списывать.</p></div></section></div>
    <div className="catalogHead"><h3>Магазин наград</h3></div>{!member?<LiveLoading/>:rewards.length?<div className="rewardCatalog">{rewards.map(reward=><article key={String(reward.id)}>{reward.image_url?<img className="rewardArt" src={String(reward.image_url)} alt=""/>:<div className="rewardArt">D</div>}<h3>{String(reward.name)}</h3><p>{String(reward.description||"Описание пока не добавлено")}</p><button disabled>{Number(reward.cost||0)} DC · Обмен через администратора</button></article>)}</div>:<LiveEmpty title="Наград для обмена пока нет" text="Магазин появится после добавления реальных товаров или привилегий администратором."/>}
  </div>;
}

function ProfileView({ go }: { go: Go }) {
  const badges=[['★','Сила команды','gold'],['10','10 мероприятий','violet'],['♡','Волонтёр','green'],['↗','Лидер клуба','blue'],['⚡','Спортивный активист','orange'],['?','Амбассадор ЕАГИ','locked']];
  return <div className="pageContent"><div className="profileHero"><div className="profileAvatar">DK<span>✓</span></div><div><span>ЦИФРОВОЙ ПРОФИЛЬ СТУДЕНТА</span><h2>Досмухамед Кемелбеков</h2><p>ЮТК-25 · Юриспруденция · 3 курс</p><div className="profileChips"><b>Level 7 · Leader</b><b>#12 в рейтинге</b><b>23 события</b></div></div><button>Поделиться профилем ↗</button></div>
    <div className="profileGrid"><section className="sectionCard profileLevel"><div className="levelTop light"><span>ПРОГРЕСС УРОВНЯ</span><b>72%</b></div><h3>2 450 <small>XP</small></h3><div className="progress light"><i style={{width:'72%'}}/></div><p>Ещё 550 XP до уровня «Амбассадор»</p><div className="levelPath"><span className="done">✓<b>Активист</b></span><i/><span className="current">7<b>Лидер</b></span><i/><span>8<b>Амбассадор</b></span></div></section><section className="sectionCard profileCoin"><span>БАЛАНС</span><h3>1 280 <small>DC Coins</small></h3><p>За всё время заработано 2 640 DC</p><button onClick={()=>go('rewards')}>Открыть Rewards →</button></section></div>
    <section className="sectionCard badgeSection"><div className="sectionHead"><div><span>ЦИФРОВАЯ КОЛЛЕКЦИЯ</span><h3>Достижения <i>14</i></h3></div><button>Смотреть все →</button></div><div className="badgeGrid">{badges.map(b=><div className={b[2]} key={b[1]}><span>{b[0]}</span><b>{b[1]}</b><small>{b[2]==='locked'?'Ещё не открыто':'Получено'}</small></div>)}</div></section>
    <div className="profileColumns"><section className="sectionCard"><div className="sectionHead"><div><span>МОИ СООБЩЕСТВА</span><h3>Мой HUB</h3></div></div><div className="myClubRow"><div className="clubLogo">DS</div><div><b>DOSTEAM Community</b><span>Участник · Организатор</span></div><em>Участник</em></div><div className="myClubRow"><div className="clubLogo blueBg">ER</div><div><b>EAGI Running</b><span>Участник</span></div><em>Участник</em></div><div className="myClubRow"><div className="clubLogo purpleBg">DC</div><div><b>Debate Club</b><span>Подписка на новости</span></div><em>Подписан</em></div><div className="myClubRow"><div className="clubLogo pinkBg">MC</div><div><b>Media Club</b><span>Заявка отправлена 20 августа</span></div><em className="pending">На рассмотрении</em></div></section><section className="sectionCard activityTimeline"><div className="sectionHead"><div><span>ПОРТФОЛИО</span><h3>Последняя активность</h3></div></div>{[['18 авг','Волонтёр · EAGI CUP','+120 XP · +30 DC'],['12 авг','Участник · Debate Night','+35 XP · +10 DC'],['08 авг','Организатор · Movie Night','+150 XP · +50 DC'],['02 авг','Участник · Open Run','+40 XP · +10 DC']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><em>{x[2]}</em></div>)}</section></div>
  </div>;
}

function AdminView({ flash }: { flash: (message: string) => void }) {
  const [section,setSection]=useState('Обзор'); const adminNav=['Обзор','Студенты','Мероприятия','Клубы','Помещения','Coins','Достижения','Аналитика','Настройки'];
  const bars=[42,58,51,76,63,82,74,91,86,96,88,100];
  return <div className="pageContent adminPage"><PageIntro eyebrow="DOSTEAM CONTROL CENTER" title="Панель администратора" text="Единая картина студенческой активности в реальном времени." action={<div className="livePill"><i/> Данные обновлены сейчас</div>}/>
    <div className="adminNav">{adminNav.map(x=><button key={x} className={section===x?'active':''} onClick={()=>setSection(x)}>{x}</button>)}</div>
    <div className="adminMetrics">{[['2 847','Студентов','+124 за месяц','students'],['126','Мероприятий','18 предстоящих','events'],['34','Активных клуба','5 заявок','clubs'],['78%','Посещаемость','+6.4% к семестру','rate'],['42.8K','DC Coins выдано','18.2K потрачено','coins'],['67%','Загрузка помещений','24 бронирования','rooms']].map(x=><article key={x[1]}><span className={x[3]}>◇</span><div><small>{x[1]}</small><b>{x[0]}</b><p>{x[2]}</p></div></article>)}</div>
    <div className="analyticsGrid"><section className="sectionCard chartCard"><div className="sectionHead"><div><span>ENGAGEMENT</span><h3>Активность студентов</h3></div><select><option>Последние 30 дней</option></select></div><div className="chartLegend"><span><i className="yellowDot"/>Регистрации</span><span><i className="darkDot"/>Посещения</span></div><div className="barChart">{bars.map((b,i)=><div key={i}><i style={{height:`${b}%`}}/><em style={{height:`${b*.72}%`}}/><small>{i%2===0?`${i+1} авг`:''}</small></div>)}</div></section><section className="sectionCard attendanceCard"><div className="sectionHead"><div><span>КОНВЕРСИЯ</span><h3>Посещаемость</h3></div></div><div className="attendanceDonut"><div><b>78%</b><span>Attendance rate</span></div></div><div className="attendRows"><span><i className="reg"/>Registered <b>3 842</b></span><span><i className="att"/>Attended <b>2 997</b></span><span><i className="no"/>No-show <b>845</b></span></div></section></div>
    <div className="adminBottom"><section className="sectionCard"><div className="sectionHead"><div><span>ТРЕБУЮТ РЕШЕНИЯ</span><h3>Новые заявки</h3></div><button>Все заявки →</button></div>{[['Новый клуб','EAGI Tech Club','Сегодня, 14:20'],['Бронирование','Актовый зал · 27 августа','Сегодня, 12:05'],['Новый клуб','Photography Club','Вчера, 18:40']].map((x,i)=><div className="requestRow" key={x[1]}><span>{i===1?'▦':'◎'}</span><div><small>{x[0]}</small><b>{x[1]}</b><em>{x[2]}</em></div><button onClick={()=>flash(`${x[1]} — одобрено`)}>Одобрить</button><button onClick={()=>flash(`${x[1]} — отклонено`)}>×</button></div>)}</section><section className="sectionCard"><div className="sectionHead"><div><span>БЛИЖАЙШЕЕ</span><h3>События сегодня</h3></div></div>{[['16:00','Welcome Day','87 / 120'],['17:30','Club Leaders Meetup','24 / 30'],['18:30','Open Run','46 / 60']].map(x=><div className="adminEvent" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><em>{x[2]}</em></div>)}</section></div>
  </div>;
}
