"use client";

import { useEffect,useRef,useState } from "react";

type Result={ok?:boolean;already?:boolean;name?:string;event?:string;xp?:number;coins?:number;level?:string;error?:string};

export default function ScanClient(){
  const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const [code,setCode]=useState("");const [camera,setCamera]=useState(false);const [result,setResult]=useState<Result|null>(null);const [busy,setBusy]=useState(false);
  useEffect(()=>()=>stream.current?.getTracks().forEach(t=>t.stop()),[]);
  const submit=async(raw=code)=>{const cleaned=raw.includes("code=")?new URL(raw).searchParams.get("code")||raw:raw;setBusy(true);setResult(null);try{const r=await fetch("/api/scan",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:cleaned})});setResult(await r.json());if(r.ok)setCode("")}catch{setResult({error:"Не удалось связаться с сервером"})}finally{setBusy(false)}};
  const start=async()=>{try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:"environment"},audio:false});stream.current=s;if(video.current){video.current.srcObject=s;await video.current.play()}setCamera(true);const Detector=(window as unknown as {BarcodeDetector?:new(o:{formats:string[]})=>{detect:(v:HTMLVideoElement)=>Promise<{rawValue:string}[]>}}).BarcodeDetector;if(Detector){const d=new Detector({formats:["qr_code"]});const timer=window.setInterval(async()=>{if(!video.current)return;const codes=await d.detect(video.current).catch(()=>[]);if(codes[0]){window.clearInterval(timer);s.getTracks().forEach(t=>t.stop());setCamera(false);void submit(codes[0].rawValue)}},500)}}catch{setResult({error:"Камера недоступна. Введите код вручную."})}};
  return <main className="scanPage"><header><a href="/hub">← HUB</a><b>DOSTEAM <span>SCAN</span></b><a href="/join">Личный кабинет ↗</a></header><section><span>КОНТРОЛЬ ПОСЕЩАЕМОСТИ</span><h1>Сканер QR-билетов</h1><p>Один билет можно отметить только один раз. XP и DC Coins начисляются автоматически.</p><div className={`cameraBox ${camera?"active":""}`}><video ref={video} playsInline muted/><div className="scanFrame"><i/><i/><i/><i/></div>{!camera&&<button onClick={start}><strong>⌗</strong><b>Включить камеру</b><small>Разрешите доступ к камере телефона</small></button>}</div><div className="manualCode"><span>ИЛИ ВВЕДИТЕ КОД БИЛЕТА</span><div><input value={code} onChange={e=>setCode(e.target.value.toUpperCase())} placeholder="DST-XXXXXXXXXXXX"/><button disabled={!code||busy} onClick={()=>submit()}>{busy?"…":"Проверить"}</button></div></div>{result&&<div className={`scanResult ${result.ok?"success":"fail"}`}><div>{result.ok?"✓":"!"}</div><h2>{result.ok?(result.already?"Уже отмечен":"Посещение подтверждено"):"Билет не принят"}</h2>{result.ok?<><b>{result.name}</b><p>{result.event}</p><span>+{result.xp} XP &nbsp; · &nbsp; +{result.coins} DC</span></>:<p>{result.error}</p>}</div>}</section></main>}
